Fix: Workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,5 +36,7 @@ jobs:
 
       - name: Restart service
         run: |
-          systemctl restart --user userbot.service || echo "Service not installed!"
+          cd /opt/UserBot/script
+          ./svc.sh stop || echo "Stopped failed"
+          ./svc.sh start || echo "Start failed"
           echo "Done!"
